[package]
name = "colors"
version = "0.1.0"
authors = ["Sander Hahn <sanderhahn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
png = "0.16.8"
